name: hello-world

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World"

  my-job2:
    needs: my-job  
    runs-on: ubuntu-latest
    steps:
      - name: my-step2
        run: echo "Second job, runs only after the first job"
